/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gastroclinica;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Geek
 */
public class IngresoNvoCliente extends javax.swing.JFrame {

    /**
     * Creates new form IngresoNvoCliente
     */
    Connection conexion;
    BusquedaProducto obj = new BusquedaProducto();
    public IngresoNvoCliente() {
        initComponents();
        establecerConexion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextNit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TextNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        GuardarClientes = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso Clientes");
        getContentPane().setLayout(null);

        TextNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNitActionPerformed(evt);
            }
        });
        getContentPane().add(TextNit);
        TextNit.setBounds(112, 107, 189, 37);

        jLabel1.setText("N.I.T.:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(56, 117, 38, 16);
        getContentPane().add(TextNombre);
        TextNombre.setBounds(112, 156, 189, 37);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 166, 54, 16);
        getContentPane().add(TextApellido);
        TextApellido.setBounds(112, 205, 189, 37);

        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(38, 215, 56, 16);
        getContentPane().add(TextDireccion);
        TextDireccion.setBounds(112, 254, 189, 37);

        jLabel4.setText("Dirección:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 264, 64, 16);

        GuardarClientes.setText("Guardar");
        GuardarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarClientesActionPerformed(evt);
            }
        });
        getContentPane().add(GuardarClientes);
        GuardarClientes.setBounds(61, 309, 93, 29);

        CancelButton.setText("Cancelar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton);
        CancelButton.setBounds(203, 309, 98, 29);

        jLabel5.setFont(new java.awt.Font("Seravek", 0, 24)); // NOI18N
        jLabel5.setText("CLIENTES");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(6, 20, 98, 31);

        jLabel6.setText("AQUI PUEDES INGRESAR LOS DATOS DE TU CLIENTE . . .");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 57, 347, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarClientesActionPerformed
        
            // TODO add your handling code here:
            
           Insertar(TextNombre.getText(), TextApellido.getText(), TextDireccion.getText(), TextNit.getText());
           
         
            
        
    }//GEN-LAST:event_GuardarClientesActionPerformed

    private void TextNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNitActionPerformed
        
    }//GEN-LAST:event_TextNitActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        TextNombre.setText("");
        TextApellido.setText("");
        TextDireccion.setText("");
        TextNit.setText("");
        
        
        
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoNvoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoNvoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoNvoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoNvoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoNvoCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton GuardarClientes;
    private javax.swing.JTextField TextApellido;
    private javax.swing.JTextField TextDireccion;
    private javax.swing.JTextField TextNit;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
public void Insertar(String nombre, String apellido, String direccion, String nit){
       
        try{
            PreparedStatement pst = conexion.prepareStatement("insert into Cliente(Nombre, Apellido, Ciudad, NIT) values(?,?,?,?)");
                                   
                pst.setString(1, nombre);
                pst.setString(2, apellido);
                pst.setString(3, direccion);
                pst.setString(4, nit);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Se ha ingresado el Cliente exitosamente!");
                 int n = JOptionPane.showConfirmDialog(null, "Deseas ingresar un nuevo cliente?", "Confirmacion", JOptionPane.YES_NO_OPTION);

                    if(true){
                        TextNit.setText("");
                        TextNombre.setText("");
                        TextApellido.setText("");
                        TextDireccion.setText("");
                        TextNit.requestFocus();
                    }obj.show();
                            
                         
            
           }catch(Exception e){
               
           }             
     }

     public void validadNit(){
         
        
     
     
     }

     private void establecerConexion() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/DBGastroClinica", "root", "mju7cde3");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
           
        }
        
    }
}
