/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gastroclinica;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo López
 */
public class Presentacion extends javax.swing.JFrame {

    Connection conexion;
    int id=0;String presentacion="";
    /**
     * Creates new form Presentacion
     */
    public Presentacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        jButton4.setEnabled(false);
        establecerConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("Presentacion:");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        // TODO add your handling code here:
//        try {
//            conexion.close();
//        } catch (SQLException ex) {
//            Logger.getLogger(TipoTelefono.class.getName()).log(Level.SEVERE, null, ex);
//        }
        AgregarProducto.actualizarPres=true;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText()!=null&&jTextField1.getText().compareTo("")!=0){
            presentacion=jTextField1.getText();
            ResultSet verificar=devolverResultado("Select* from Presentacion where Presentacion=\""+presentacion+"\";");
            try {
                if(verificar.next()==true){
                    JOptionPane.showMessageDialog(null,"Presentacion de producto encontrada.","",JOptionPane.INFORMATION_MESSAGE);
                    jButton3.setEnabled(false);jButton4.setEnabled(true);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Presentacion de producto no encontrada.","",JOptionPane.ERROR_MESSAGE);
                    jButton3.setEnabled(true);jButton4.setEnabled(false);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Presentacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            //this.show(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"Ingrese la presentacion.","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText()!=null&&jTextField1.getText().compareTo("")!=0){
            presentacion=jTextField1.getText();
            ResultSet verificar=devolverResultado("Select* from Presentacion where Presentacion=\""+presentacion+"\";");
            try {
                if(verificar.next()==true){
                    JOptionPane.showMessageDialog(null,"La presentacion ingresada ya existe en la base de datos.","",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    consultaInsertar("insert into Presentacion(Presentacion) values(\""+presentacion+"\");");
                    JOptionPane.showMessageDialog(null,"Presentacion creada con exito.","",JOptionPane.INFORMATION_MESSAGE);
                    AgregarProducto.actualizarPres=true;
                    this.dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Presentacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            //this.show(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"Ingrese la presentacion.","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText()!=null&&jTextField1.getText().compareTo("")!=0){
            String anterior=presentacion;
            presentacion=jTextField1.getText();
            ResultSet verificar=devolverResultado("Select* from Presentacion where Presentacion=\""+presentacion+"\";");
            try {
                if(verificar.next()==true){
                    JOptionPane.showMessageDialog(null,"Imposible renombrar, presentacion existente.","",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    String modificar="update Presentacion set Presentacion=\""+presentacion+"\" where Presentacion=\""+anterior+"\";";
                    consultaInsertar(modificar);
                    JOptionPane.showMessageDialog(null,"Presentacion renombrada.","",JOptionPane.INFORMATION_MESSAGE);
                    jButton3.setEnabled(true);jButton4.setEnabled(false);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Presentacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            //this.show(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"Ingrese la presentacion.","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
public ResultSet devolverResultado(String consulta){
            ResultSet devolver = null;
        try {
            Statement s=conexion.createStatement();
            devolver=s.executeQuery(consulta);
        } catch (SQLException ex) {
            Logger.getLogger(Presentacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        return devolver;
    }
    public void consultaInsertar(String sql){
        try {
            Statement insertar=conexion.createStatement();
            insertar.executeUpdate(sql);
            //JOptionPane.showMessageDialog(null, "Consulta realizada con exito", "", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al momento de almacenar la informacion", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void establecerConexion() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/DBGastroClinica", "root", "ingenieria");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            //return false;
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
           // return false;
        }
        //return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
