/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gastroclinica;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pablo López
 */
public class PrincipalUsuario extends javax.swing.JFrame {
    int usuario=0;
    Connection conexion;
    ArrayList<String> modulosPermitidos=new ArrayList<String>();
    /**
     * Creates new form PrincipalUsuario
     */
    public PrincipalUsuario() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public PrincipalUsuario(int usuario,Connection conexion) {
        this.usuario=usuario;
        this.conexion=conexion;
        initComponents();
        setLocationRelativeTo(null);
        privilegiosUsuario();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jMenu1.setText("Archivo");

        jMenu3.setText("Crear");

        jMenuItem1.setText("Empleado");
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Proveedor");
        jMenu3.add(jMenuItem2);

        jMenuItem11.setText("Cliente");
        jMenu3.add(jMenuItem11);

        jMenu1.add(jMenu3);

        jMenu4.setText("Buscar");

        jMenuItem3.setText("Empleados");
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Proveedores");
        jMenu4.add(jMenuItem4);

        jMenu1.add(jMenu4);

        jMenu6.setText("Ventas");

        jMenuItem9.setText("Nueva venta");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenu1.add(jMenu6);

        jMenu7.setText("Compras");

        jMenuItem10.setText("Nueva compra");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenu1.add(jMenu7);

        jMenu8.setText("Reportes");
        jMenu1.add(jMenu8);

        jMenuItem8.setText("Inventario");
        jMenu1.add(jMenuItem8);

        jMenuItem7.setText("Salir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Usuario");

        jMenuItem5.setText("Informacion");
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Ayuda");

        jMenuItem6.setText("Acerca de");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
//        // TODO add your handling code here:
//        try {
//            conexion.close();
//        } catch (SQLException ex) {
//            Logger.getLogger(VentanaUsuarioGerente.class.getName()).log(Level.SEVERE, null, ex);
//        }
        Login nuevo = new Login();
        nuevo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        Compra nueva=new Compra(usuario,conexion);
        nueva.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here: BusquedaProducto
        BusquedaProducto busqueda = new BusquedaProducto();
        busqueda.asignarUsuario(usuario);
        busqueda.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void privilegiosUsuario(){
        ResultSet resultado1=resultadoConsulta("SELECT* FROM Usuario where id="+usuario+";");
        try {
            resultado1.next();
            int tipoUsuario=resultado1.getInt("Tipo_Usuario_id");
            ResultSet resultado2=resultadoConsulta("select P.Modulo from Permiso_Usuario PU inner join Permiso P on PU.Permiso_id=P.id where PU.Tipo_Usuario_id="+tipoUsuario+";");
            while(resultado2.next()==true){
                modulosPermitidos.add(resultado2.getString("Modulo"));
                System.out.println(resultado2.getString("Modulo"));
                habilitarModulos();
            }
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void habilitarModulos(){
        Iterator<String> iterador=modulosPermitidos.iterator();
        while(iterador.hasNext()){
            String modulo=iterador.next();
            if(modulo.compareTo("Ventas")==0){
            
            }
            if(modulo.compareTo("Compras")==0){
            
            }
            if(modulo.compareTo("Reportes")==0){
            
            }
            if(modulo.compareTo("Inventario")==0){
            
            }
            if(modulo.compareTo("Administrativo")==0){
            
            }
        }
    }
    public ResultSet resultadoConsulta(String consulta){
            ResultSet devolver = null;
        try {
            Statement s=conexion.createStatement();
            devolver=s.executeQuery(consulta);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return devolver;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
